// Mocks generated by Mockito 5.4.6 from annotations
// in nostr_social_example/test/widget/tor_error_handling_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:flutter_embedded_nostr_relay/flutter_embedded_nostr_relay.dart'
    as _i2;
import 'package:logging/logging.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nostr_social_example/src/providers/relay_provider.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmbeddedNostrRelay_0 extends _i1.SmartFake
    implements _i2.EmbeddedNostrRelay {
  _FakeEmbeddedNostrRelay_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTorConfig_1 extends _i1.SmartFake implements _i2.TorConfig {
  _FakeTorConfig_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayInfo_2 extends _i1.SmartFake implements _i2.RelayInfo {
  _FakeRelayInfo_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RelayProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockRelayProvider extends _i1.Mock implements _i3.RelayProvider {
  MockRelayProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isInitializing =>
      (super.noSuchMethod(
            Invocation.getter(#isInitializing),
            returnValue: false,
          )
          as bool);

  @override
  Map<String, int> get stats =>
      (super.noSuchMethod(
            Invocation.getter(#stats),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, dynamic> get subscriptionStats =>
      (super.noSuchMethod(
            Invocation.getter(#subscriptionStats),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get p2pEnabled =>
      (super.noSuchMethod(Invocation.getter(#p2pEnabled), returnValue: false)
          as bool);

  @override
  List<_i2.Peer> get discoveredPeers =>
      (super.noSuchMethod(
            Invocation.getter(#discoveredPeers),
            returnValue: <_i2.Peer>[],
          )
          as List<_i2.Peer>);

  @override
  List<String> get externalRelays =>
      (super.noSuchMethod(
            Invocation.getter(#externalRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  Map<String, bool> get relayConnections =>
      (super.noSuchMethod(
            Invocation.getter(#relayConnections),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  bool get isOnline =>
      (super.noSuchMethod(Invocation.getter(#isOnline), returnValue: false)
          as bool);

  @override
  _i2.EmbeddedNostrRelay get relay =>
      (super.noSuchMethod(
            Invocation.getter(#relay),
            returnValue: _FakeEmbeddedNostrRelay_0(
              this,
              Invocation.getter(#relay),
            ),
          )
          as _i2.EmbeddedNostrRelay);

  @override
  _i2.TorConfig get torConfig =>
      (super.noSuchMethod(
            Invocation.getter(#torConfig),
            returnValue: _FakeTorConfig_1(this, Invocation.getter(#torConfig)),
          )
          as _i2.TorConfig);

  @override
  bool get torForRelays =>
      (super.noSuchMethod(Invocation.getter(#torForRelays), returnValue: false)
          as bool);

  @override
  bool get torForVideos =>
      (super.noSuchMethod(Invocation.getter(#torForVideos), returnValue: false)
          as bool);

  @override
  bool get torAvailable =>
      (super.noSuchMethod(Invocation.getter(#torAvailable), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize({
    _i5.Level? logLevel = _i5.Level.INFO,
    bool? enableGarbageCollection = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #logLevel: logLevel,
              #enableGarbageCollection: enableGarbageCollection,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> shutdown() =>
      (super.noSuchMethod(
            Invocation.method(#shutdown, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> enableP2PSync({
    List<_i2.TransportType>? transports = const [
      _i2.TransportType.ble,
      _i2.TransportType.wifiDirect,
    ],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enableP2PSync, [], {#transports: transports}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disableP2PSync() =>
      (super.noSuchMethod(
            Invocation.method(#disableP2PSync, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addExternalRelay(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#addExternalRelay, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeExternalRelay(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#removeExternalRelay, [url]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateStats() =>
      (super.noSuchMethod(
            Invocation.method(#updateStats, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i2.RelayInfo getRelayInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayInfo, []),
            returnValue: _FakeRelayInfo_2(
              this,
              Invocation.method(#getRelayInfo, []),
            ),
          )
          as _i2.RelayInfo);

  @override
  _i4.Future<void> setTorForRelays(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setTorForRelays, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setTorForVideos(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setTorForVideos, [enabled]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateTorConfig(_i2.TorConfig? newConfig) =>
      (super.noSuchMethod(
            Invocation.method(#updateTorConfig, [newConfig]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
