// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_embedded_nostr_relay/test/unit/network/event_version_sync_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_embedded_nostr_relay/src/models/filter.dart' as _i5;
import 'package:flutter_embedded_nostr_relay/src/models/nostr_event.dart'
    as _i4;
import 'package:flutter_embedded_nostr_relay/src/network/external_relay_client.dart'
    as _i6;
import 'package:flutter_embedded_nostr_relay/src/storage/event_store.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i2.EventStore {
  MockEventStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> storeEvent(_i4.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvent, [event]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<int> storeEvents(List<_i4.NostrEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvents, [events]),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.NostrEvent>> queryEvents(List<_i5.Filter>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#queryEvents, [filters]),
            returnValue: _i3.Future<List<_i4.NostrEvent>>.value(
              <_i4.NostrEvent>[],
            ),
          )
          as _i3.Future<List<_i4.NostrEvent>>);

  @override
  _i3.Future<_i4.NostrEvent?> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i3.Future<_i4.NostrEvent?>.value(),
          )
          as _i3.Future<_i4.NostrEvent?>);

  @override
  _i3.Future<_i4.NostrEvent?> getEventById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i3.Future<_i4.NostrEvent?>.value(),
          )
          as _i3.Future<_i4.NostrEvent?>);

  @override
  _i3.Future<_i4.NostrEvent?> getLatestReplaceableEvent(
    int? kind,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestReplaceableEvent, [kind, pubkey]),
            returnValue: _i3.Future<_i4.NostrEvent?>.value(),
          )
          as _i3.Future<_i4.NostrEvent?>);

  @override
  _i3.Future<_i4.NostrEvent?> getLatestParameterizedReplaceableEvent(
    int? kind,
    String? pubkey,
    String? dTag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestParameterizedReplaceableEvent, [
              kind,
              pubkey,
              dTag,
            ]),
            returnValue: _i3.Future<_i4.NostrEvent?>.value(),
          )
          as _i3.Future<_i4.NostrEvent?>);

  @override
  _i3.Future<void> deleteEvents(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvents, [eventIds]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<String>> getEventIdsInRange(int? startTime, int? endTime) =>
      (super.noSuchMethod(
            Invocation.method(#getEventIdsInRange, [startTime, endTime]),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<int> garbageCollect({
    required int? retentionDays,
    List<String>? preserveAuthors,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#garbageCollect, [], {
              #retentionDays: retentionDays,
              #preserveAuthors: preserveAuthors,
            }),
            returnValue: _i3.Future<int>.value(0),
          )
          as _i3.Future<int>);
}

/// A class which mocks [ExternalRelayClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockExternalRelayClient extends _i1.Mock
    implements _i6.ExternalRelayClient {
  MockExternalRelayClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i7.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  set onEvent(dynamic Function(_i4.NostrEvent)? _onEvent) => super.noSuchMethod(
    Invocation.setter(#onEvent, _onEvent),
    returnValueForMissingStub: null,
  );

  @override
  set onEose(dynamic Function(String)? _onEose) => super.noSuchMethod(
    Invocation.setter(#onEose, _onEose),
    returnValueForMissingStub: null,
  );

  @override
  set onOk(dynamic Function(String, bool, String?)? _onOk) =>
      super.noSuchMethod(
        Invocation.setter(#onOk, _onOk),
        returnValueForMissingStub: null,
      );

  @override
  set onNotice(dynamic Function(String)? _onNotice) => super.noSuchMethod(
    Invocation.setter(#onNotice, _onNotice),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> connect() =>
      (super.noSuchMethod(
            Invocation.method(#connect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> handleMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#handleMessage, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> sendRequest(
    String? subscriptionId,
    List<_i5.Filter>? filters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendRequest, [subscriptionId, filters]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> sendEvent(_i4.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#sendEvent, [event]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> closeSubscription(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#closeSubscription, [subscriptionId]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
