// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_embedded_nostr_relay/test/unit/network/websocket_server_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_embedded_nostr_relay/src/core/subscription_manager.dart'
    as _i3;
import 'package:flutter_embedded_nostr_relay/src/models/filter.dart' as _i7;
import 'package:flutter_embedded_nostr_relay/src/models/nostr_event.dart'
    as _i6;
import 'package:flutter_embedded_nostr_relay/src/models/relay_message.dart'
    as _i5;
import 'package:flutter_embedded_nostr_relay/src/models/subscription.dart'
    as _i2;
import 'package:flutter_embedded_nostr_relay/src/storage/event_store.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubscription_0 extends _i1.SmartFake implements _i2.Subscription {
  _FakeSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i3.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Subscription> handleReq(
    String? clientId,
    _i5.ReqMessage? reqMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleReq, [clientId, reqMessage]),
            returnValue: _i4.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#handleReq, [clientId, reqMessage]),
              ),
            ),
          )
          as _i4.Future<_i2.Subscription>);

  @override
  _i4.Future<bool> handleClose(
    String? clientId,
    _i5.CloseMessage? closeMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleClose, [clientId, closeMessage]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> routeEvent(_i6.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#routeEvent, [event]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> handleClientDisconnect(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#handleClientDisconnect, [clientId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  List<_i2.Subscription> getSubscriptionsForClient(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionsForClient, [clientId]),
            returnValue: <_i2.Subscription>[],
          )
          as List<_i2.Subscription>);

  @override
  int getActiveClientsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveClientsCount, []),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, List<_i7.Filter>> getAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubscriptions, []),
            returnValue: <String, List<_i7.Filter>>{},
          )
          as Map<String, List<_i7.Filter>>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i8.EventStore {
  MockEventStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> storeEvent(_i6.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvent, [event]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> storeEvents(List<_i6.NostrEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvents, [events]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<List<_i6.NostrEvent>> queryEvents(List<_i7.Filter>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#queryEvents, [filters]),
            returnValue: _i4.Future<List<_i6.NostrEvent>>.value(
              <_i6.NostrEvent>[],
            ),
          )
          as _i4.Future<List<_i6.NostrEvent>>);

  @override
  _i4.Future<_i6.NostrEvent?> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i4.Future<_i6.NostrEvent?>.value(),
          )
          as _i4.Future<_i6.NostrEvent?>);

  @override
  _i4.Future<_i6.NostrEvent?> getEventById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i4.Future<_i6.NostrEvent?>.value(),
          )
          as _i4.Future<_i6.NostrEvent?>);

  @override
  _i4.Future<_i6.NostrEvent?> getLatestReplaceableEvent(
    int? kind,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestReplaceableEvent, [kind, pubkey]),
            returnValue: _i4.Future<_i6.NostrEvent?>.value(),
          )
          as _i4.Future<_i6.NostrEvent?>);

  @override
  _i4.Future<_i6.NostrEvent?> getLatestParameterizedReplaceableEvent(
    int? kind,
    String? pubkey,
    String? dTag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestParameterizedReplaceableEvent, [
              kind,
              pubkey,
              dTag,
            ]),
            returnValue: _i4.Future<_i6.NostrEvent?>.value(),
          )
          as _i4.Future<_i6.NostrEvent?>);

  @override
  _i4.Future<void> deleteEvents(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvents, [eventIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getEventIdsInRange(int? startTime, int? endTime) =>
      (super.noSuchMethod(
            Invocation.method(#getEventIdsInRange, [startTime, endTime]),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  _i4.Future<int> garbageCollect({
    required int? retentionDays,
    List<String>? preserveAuthors,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#garbageCollect, [], {
              #retentionDays: retentionDays,
              #preserveAuthors: preserveAuthors,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
