// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_embedded_nostr_relay/test/function_channel_relay_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_embedded_nostr_relay/src/core/embedded_nostr_relay.dart'
    as _i11;
import 'package:flutter_embedded_nostr_relay/src/core/function_channel_relay.dart'
    as _i4;
import 'package:flutter_embedded_nostr_relay/src/core/subscription_manager.dart'
    as _i5;
import 'package:flutter_embedded_nostr_relay/src/models/filter.dart' as _i9;
import 'package:flutter_embedded_nostr_relay/src/models/nostr_event.dart'
    as _i8;
import 'package:flutter_embedded_nostr_relay/src/models/relay_info.dart' as _i3;
import 'package:flutter_embedded_nostr_relay/src/models/relay_message.dart'
    as _i7;
import 'package:flutter_embedded_nostr_relay/src/models/subscription.dart'
    as _i2;
import 'package:flutter_embedded_nostr_relay/src/storage/event_store.dart'
    as _i10;
import 'package:logging/logging.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSubscription_0 extends _i1.SmartFake implements _i2.Subscription {
  _FakeSubscription_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayInfo_1 extends _i1.SmartFake implements _i3.RelayInfo {
  _FakeRelayInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionChannelSession_2 extends _i1.SmartFake
    implements _i4.FunctionChannelSession {
  _FakeFunctionChannelSession_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SubscriptionManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSubscriptionManager extends _i1.Mock
    implements _i5.SubscriptionManager {
  MockSubscriptionManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Subscription> handleReq(
    String? clientId,
    _i7.ReqMessage? reqMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleReq, [clientId, reqMessage]),
            returnValue: _i6.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#handleReq, [clientId, reqMessage]),
              ),
            ),
          )
          as _i6.Future<_i2.Subscription>);

  @override
  _i6.Future<bool> handleClose(
    String? clientId,
    _i7.CloseMessage? closeMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleClose, [clientId, closeMessage]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int> routeEvent(_i8.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#routeEvent, [event]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<void> handleClientDisconnect(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#handleClientDisconnect, [clientId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  List<_i2.Subscription> getSubscriptionsForClient(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionsForClient, [clientId]),
            returnValue: <_i2.Subscription>[],
          )
          as List<_i2.Subscription>);

  @override
  int getActiveClientsCount() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveClientsCount, []),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, List<_i9.Filter>> getAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubscriptions, []),
            returnValue: <String, List<_i9.Filter>>{},
          )
          as Map<String, List<_i9.Filter>>);

  @override
  Map<String, dynamic> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [EventStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventStore extends _i1.Mock implements _i10.EventStore {
  MockEventStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> storeEvent(_i8.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvent, [event]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<int> storeEvents(List<_i8.NostrEvent>? events) =>
      (super.noSuchMethod(
            Invocation.method(#storeEvents, [events]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<List<_i8.NostrEvent>> queryEvents(List<_i9.Filter>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#queryEvents, [filters]),
            returnValue: _i6.Future<List<_i8.NostrEvent>>.value(
              <_i8.NostrEvent>[],
            ),
          )
          as _i6.Future<List<_i8.NostrEvent>>);

  @override
  _i6.Future<_i8.NostrEvent?> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i6.Future<_i8.NostrEvent?>.value(),
          )
          as _i6.Future<_i8.NostrEvent?>);

  @override
  _i6.Future<_i8.NostrEvent?> getEventById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEventById, [id]),
            returnValue: _i6.Future<_i8.NostrEvent?>.value(),
          )
          as _i6.Future<_i8.NostrEvent?>);

  @override
  _i6.Future<_i8.NostrEvent?> getLatestReplaceableEvent(
    int? kind,
    String? pubkey,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestReplaceableEvent, [kind, pubkey]),
            returnValue: _i6.Future<_i8.NostrEvent?>.value(),
          )
          as _i6.Future<_i8.NostrEvent?>);

  @override
  _i6.Future<_i8.NostrEvent?> getLatestParameterizedReplaceableEvent(
    int? kind,
    String? pubkey,
    String? dTag,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getLatestParameterizedReplaceableEvent, [
              kind,
              pubkey,
              dTag,
            ]),
            returnValue: _i6.Future<_i8.NostrEvent?>.value(),
          )
          as _i6.Future<_i8.NostrEvent?>);

  @override
  _i6.Future<void> deleteEvents(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvents, [eventIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getEventIdsInRange(int? startTime, int? endTime) =>
      (super.noSuchMethod(
            Invocation.method(#getEventIdsInRange, [startTime, endTime]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<int> garbageCollect({
    required int? retentionDays,
    List<String>? preserveAuthors,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#garbageCollect, [], {
              #retentionDays: retentionDays,
              #preserveAuthors: preserveAuthors,
            }),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);
}

/// A class which mocks [EmbeddedNostrRelay].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmbeddedNostrRelay extends _i1.Mock
    implements _i11.EmbeddedNostrRelay {
  MockEmbeddedNostrRelay() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i6.Stream<_i8.NostrEvent> get eventStream =>
      (super.noSuchMethod(
            Invocation.getter(#eventStream),
            returnValue: _i6.Stream<_i8.NostrEvent>.empty(),
          )
          as _i6.Stream<_i8.NostrEvent>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i6.Future<void> initialize({
    _i12.Level? logLevel = _i12.Level.INFO,
    bool? enableGarbageCollection = true,
    bool? useFunctionChannel = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #logLevel: logLevel,
              #enableGarbageCollection: enableGarbageCollection,
              #useFunctionChannel: useFunctionChannel,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i2.Subscription> handleReq(
    String? clientId,
    _i7.ReqMessage? reqMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleReq, [clientId, reqMessage]),
            returnValue: _i6.Future<_i2.Subscription>.value(
              _FakeSubscription_0(
                this,
                Invocation.method(#handleReq, [clientId, reqMessage]),
              ),
            ),
          )
          as _i6.Future<_i2.Subscription>);

  @override
  _i6.Future<bool> handleClose(
    String? clientId,
    _i7.CloseMessage? closeMessage,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleClose, [clientId, closeMessage]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> handleClientDisconnect(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#handleClientDisconnect, [clientId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i2.Subscription subscribe({
    required List<_i9.Filter>? filters,
    dynamic Function(_i8.NostrEvent)? onEvent,
    dynamic Function()? onEose,
    dynamic Function(String)? onError,
    String? subscriptionId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#subscribe, [], {
              #filters: filters,
              #onEvent: onEvent,
              #onEose: onEose,
              #onError: onError,
              #subscriptionId: subscriptionId,
            }),
            returnValue: _FakeSubscription_0(
              this,
              Invocation.method(#subscribe, [], {
                #filters: filters,
                #onEvent: onEvent,
                #onEose: onEose,
                #onError: onError,
                #subscriptionId: subscriptionId,
              }),
            ),
          )
          as _i2.Subscription);

  @override
  _i6.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> publish(_i8.NostrEvent? event) =>
      (super.noSuchMethod(
            Invocation.method(#publish, [event]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<List<_i8.NostrEvent>> queryEvents(List<_i9.Filter>? filters) =>
      (super.noSuchMethod(
            Invocation.method(#queryEvents, [filters]),
            returnValue: _i6.Future<List<_i8.NostrEvent>>.value(
              <_i8.NostrEvent>[],
            ),
          )
          as _i6.Future<List<_i8.NostrEvent>>);

  @override
  _i6.Future<_i8.NostrEvent?> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i6.Future<_i8.NostrEvent?>.value(),
          )
          as _i6.Future<_i8.NostrEvent?>);

  @override
  _i6.Future<void> deleteEvents(List<String>? eventIds) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEvents, [eventIds]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i3.RelayInfo getRelayInfo() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayInfo, []),
            returnValue: _FakeRelayInfo_1(
              this,
              Invocation.method(#getRelayInfo, []),
            ),
          )
          as _i3.RelayInfo);

  @override
  _i6.Future<Map<String, int>> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue: _i6.Future<Map<String, int>>.value(<String, int>{}),
          )
          as _i6.Future<Map<String, int>>);

  @override
  Map<String, dynamic> getSubscriptionStats() =>
      (super.noSuchMethod(
            Invocation.method(#getSubscriptionStats, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  _i4.FunctionChannelSession createFunctionSession() =>
      (super.noSuchMethod(
            Invocation.method(#createFunctionSession, []),
            returnValue: _FakeFunctionChannelSession_2(
              this,
              Invocation.method(#createFunctionSession, []),
            ),
          )
          as _i4.FunctionChannelSession);

  @override
  _i6.Future<void> enableP2PSync({
    required List<_i11.TransportType>? transports,
    dynamic Function(_i11.Peer)? onPeerDiscovered,
    dynamic Function(_i11.Peer)? onPeerLost,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#enableP2PSync, [], {
              #transports: transports,
              #onPeerDiscovered: onPeerDiscovered,
              #onPeerLost: onPeerLost,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> addExternalRelay(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#addExternalRelay, [url]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setRelayList({
    required List<String>? read,
    required List<String>? write,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setRelayList, [], {#read: read, #write: write}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeExternalRelay(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#removeExternalRelay, [url]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> shutdown() =>
      (super.noSuchMethod(
            Invocation.method(#shutdown, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
